### ISSUE TITLE
Level/World mappings

### ISSUE THREAD

**Issue by hea3ven** [shadowfacts/1.9-Mappings#10]
I've done some of the world mappings at https://github.com/hea3ven/1.9-Mappings/commit/51d728dae5e85da6c7ef306cdd1fe051f9cefc42 , but I did it using "World" in stead of "Level". So if you guys wanna pull them, you are gonna have to manually rename them.

**Comment by FayeAlephNil** [comment]
Instead of making an issue make a pull request
