### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hea3ven** [shadowfacts/1.9-Mappings#12]
I'm wondering what's everyone stance on this topic. Personally I don't care at all what people do with my contributions, but I know not everyone shares that thought. Mainly wondering because I'd like to redistribute the mappings inside the mod's jar.

**Comment by FayeAlephNil** [comment]
Is everyone ok with the MIT license?

**Comment by shadowfacts** [comment]
If you agree with using the [MIT License](http://opensource.org/licenses/MIT) please respond saying so. If you have an alternate suggestion, please suggest it and why you think it should be used.
- [x] @shadowfacts
- [x] @Strikingwolf 
- [x] @iLexiconn 
- [x] @minecreatr 
- [x] @OdnetninI 
- [x] @hea3ven 
- [x] @VikeStep 
- [x] @fewizz 
- [x] @coolsquid

**Comment by fewizz** [comment]
agree.

**Comment by iLexiconn** [comment]
Sure

**Comment by hea3ven** [comment]
Agree.

**Comment by minecreatr** [comment]
agree

**Comment by coolsquid** [comment]
I hereby release all my contributions to this repository under the MIT license.

**Comment by OdnetninI** [comment]
agree
